# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170830_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
