# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170830_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasememo',
            name='given_memo_no',
            field=models.IntegerField(default=0),
        ),
    ]
